#!/usr/bin/env python3
"""Upload rendered video to YouTube as private — plan 0006 D7.

Handles the resumable-upload path with chunked transfer, surfaces quota/auth
errors explicitly, and never prints raw token values.

Usage:
    ./.venv/bin/python upload_video.py <mp4-path>

YouTube Data API v3 Quota Note:
    The default project quota is 10,000 units/day. A videos.insert() call costs
    1,600 units, meaning roughly 6 uploads/day is the practical ceiling for a
    new/unverified project. If uploads start failing with quota-exceeded errors,
    the only fix is to either (a) wait for the quota to reset at midnight UTC,
    or (b) file a quota-increase request with Google (typically granted within
    24h for verified, low-risk projects). See the error message for guidance.
"""
import argparse
import json
import sys
from pathlib import Path

from check_auth import get_credentials
from google.auth.exceptions import GoogleAuthError
from googleapiclient.discovery import build
from googleapiclient.errors import Error as GoogleApiClientError
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaFileUpload

# Size of each chunk in the resumable upload, in bytes.
# Chosen large enough to amortize per-request overhead, small enough to
# tolerate transient failures without re-uploading too much.
# YouTube's documented max is 256 MB per chunk; we use 8 MB as a practical
# default that balances responsiveness and efficiency.
CHUNK_SIZE = 8 * 1024 * 1024

# Path to scenes.json, relative to this script's directory.
SCENES_PATH = Path(__file__).parent / "scenes.json"


def load_scenes_metadata():
    """Load video metadata from scenes.json.

    Returns a dict with 'title' and 'description' keys suitable for YouTube
    API insertion, derived from the post path and scene headlines.
    Fails gracefully if the file is missing or malformed, using sensible defaults.
    """
    defaults = {
        "title": "Untitled video",
        "description": "Video generated by davevoyles.com video pipeline.",
    }
    try:
        with open(SCENES_PATH) as f:
            scenes = json.load(f)

        # scenes.json is expected to be an object ({"post": ..., "scenes": [...]});
        # a differently-shaped but still-valid JSON document (e.g. a bare list)
        # would raise AttributeError/TypeError on the .get() calls below, not
        # JSONDecodeError — caught alongside it so a malformed-but-parseable
        # file still falls back to defaults instead of crashing the upload.
        post_path = scenes.get("post", "").strip()
        post_slug = Path(post_path).stem if post_path else "video"

        scenes_list = scenes.get("scenes", [])
        first_headline = (
            scenes_list[0].get("headline", "").strip() if scenes_list else ""
        )
        title = first_headline if first_headline else f"Explainer: {post_slug}"

        description = (
            f"Explainer video from the article: {post_slug}\n\n"
            "Generated by davevoyles.com video pipeline. "
            "Watch the full article at https://davevoyles.com/"
        )
        return {"title": title, "description": description}
    except (FileNotFoundError, OSError, json.JSONDecodeError, AttributeError, TypeError):
        # Scenes file missing, unparseable, or not shaped as expected.
        return defaults


def upload_video(mp4_path):
    """Upload MP4 file to YouTube as a private video.

    Args:
        mp4_path: Path to the MP4 file to upload.

    Returns:
        The video ID (string) of the uploaded video.

    Raises:
        SystemExit on fatal errors (auth failure, quota exceeded, etc.).
    """
    mp4_path = Path(mp4_path)

    # Validate that the file exists and is readable.
    if not mp4_path.exists():
        print(f"error: video file not found at {mp4_path}", file=sys.stderr)
        sys.exit(1)

    if not mp4_path.is_file():
        print(
            f"error: {mp4_path} is not a regular file",
            file=sys.stderr,
        )
        sys.exit(1)

    file_size = mp4_path.stat().st_size
    print(f"Uploading {mp4_path.name} ({file_size / 1e9:.2f} GB)...")

    # Acquire OAuth credentials.
    try:
        creds = get_credentials()
    except SystemExit:
        # get_credentials() already printed a detailed error message to stderr.
        sys.exit(1)

    # Build the YouTube API client.
    youtube = build("youtube", "v3", credentials=creds, cache_discovery=False)

    # Load metadata from scenes.json.
    metadata = load_scenes_metadata()

    # Construct the request body for videos.insert().
    # The video is uploaded as private — Dave must manually flip it to
    # unlisted/public in YouTube Studio. This is a deliberate gate per ADR 0011.
    request_body = {
        "snippet": {
            "title": metadata["title"],
            "description": metadata["description"],
            "tags": ["explainer", "davevoyles"],
            "categoryId": "27",  # Education category.
        },
        "status": {
            "privacyStatus": "private",  # Never public; human must approve visibility.
            "madeForKids": False,
        },
    }

    # Build the media upload object with resumable=True to enable chunked upload.
    media = MediaFileUpload(
        str(mp4_path),
        mimetype="video/mp4",
        resumable=True,
        chunksize=CHUNK_SIZE,
    )

    # Insert the video. The insertable() method returns a request object
    # that we execute chunk by chunk.
    insert_request = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media,
    )

    # Execute the resumable upload with chunking and progress tracking.
    video_id = _execute_resumable_upload(insert_request)

    print(f"\nUpload complete. Video ID: {video_id}")
    print("Privacy status: PRIVATE (set manually in YouTube Studio)")

    return video_id


def _execute_resumable_upload(insert_request):
    """Execute the resumable upload request with chunked transfer.

    Loops over the request's next_chunk() method, printing progress and
    handling errors explicitly.

    Args:
        insert_request: A YouTube videos.insert() request with resumable=True.

    Returns:
        The video ID of the uploaded video.

    Raises:
        SystemExit on quota or auth errors.
    """
    response = None
    while response is None:
        try:
            # num_retries enables the library's own exponential-backoff retry
            # for transient errors (connection resets, timeouts, 5xx) within
            # a single chunk — without it, next_chunk() has zero retries and
            # any network blip on a large upload kills the whole transfer,
            # defeating the point of a resumable upload.
            status, response = insert_request.next_chunk(num_retries=5)
            if status:
                # Print progress as a percentage of chunks uploaded.
                # status.progress() returns a value in [0.0, 1.0].
                print(f"  Upload progress: {int(status.progress() * 100)}%")
        except HttpError as e:
            # Catch YouTube API errors (e.g. quota, auth, validation).
            error_code = e.resp.status
            try:
                error_body = json.loads(e.content)
                errors_list = error_body.get("error", {}).get("errors", [])
                error_reason = errors_list[0].get("reason", "unknown") if errors_list else "unknown"
            except (json.JSONDecodeError, KeyError, IndexError, AttributeError):
                error_reason = "unknown"

            if error_code == 403:
                if error_reason == "quotaExceeded":
                    print(
                        f"\nerror: YouTube quota exhausted (default 10,000 units/day; "
                        f"videos.insert costs 1,600 units). Retry after midnight UTC or "
                        f"request a quota increase from Google.",
                        file=sys.stderr,
                    )
                    sys.exit(1)
                else:
                    print(
                        f"\nerror: access denied (403 {error_reason}). "
                        f"Check that OAuth scope includes youtube.upload and token is valid.",
                        file=sys.stderr,
                    )
                    sys.exit(1)
            elif error_code == 401:
                print(
                    f"\nerror: authentication failed (401). "
                    f"Token may have expired. Delete ~/.config/davevoyles-video/token.json "
                    f"and re-run to re-authorize.",
                    file=sys.stderr,
                )
                sys.exit(1)
            else:
                print(
                    f"\nerror: upload failed (HTTP {error_code} {error_reason})",
                    file=sys.stderr,
                )
                sys.exit(1)
        except GoogleAuthError:
            # Token refresh or other auth-level failure (not API-level).
            # Deliberately not including str(e) — this exception class covers
            # token-refresh failures, and its message text has been observed
            # to vary by library version; matching check_auth.py's convention
            # of never letting exception text near a credential path reach
            # stderr, even indirectly.
            print(
                "\nerror: authentication error during upload. "
                "Token may have expired or a network issue occurred during refresh. "
                "Delete ~/.config/davevoyles-video/token.json and re-run to re-authorize.",
                file=sys.stderr,
            )
            sys.exit(1)
        except GoogleApiClientError as e:
            # Other googleapiclient errors (e.g. ResumableUploadError,
            # MediaUploadSizeError) not already handled by HttpError above.
            # These aren't credential-adjacent, so including the exception's
            # own message (which is typically just a plain description, e.g.
            # "invalid chunk size") is safe and useful for diagnosis.
            print(
                f"\nerror: unexpected error during upload ({e})",
                file=sys.stderr,
            )
            sys.exit(1)

    # Extract the video ID from the final response.
    video_id = response.get("id")
    if not video_id:
        print(
            "error: upload succeeded but response did not include video ID",
            file=sys.stderr,
        )
        sys.exit(1)

    return video_id


def main():
    parser = argparse.ArgumentParser(
        description="Upload a rendered video to YouTube (private visibility)"
    )
    parser.add_argument("mp4_path", help="Path to the MP4 file to upload")

    args = parser.parse_args()

    try:
        upload_video(args.mp4_path)
    except KeyboardInterrupt:
        print("\nUpload interrupted by user", file=sys.stderr)
        sys.exit(130)


if __name__ == "__main__":
    main()
