#!/usr/bin/env bash
# Local-only Hugo preview of the generated video (plan 0005 D4).
#
#   ./preview.sh          # stage video into static/ and start hugo server -D
#   ./preview.sh --stage  # stage only (no server) — used by the acceptance probe
#
# The draft post at content/posts/agent-production-system-video-preview.md carries
# draft = true, so it cannot reach a production build. static/video/ is gitignored:
# the MP4 is a ~9 MB build artifact, regenerated by ./build_video.sh all.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$ROOT/.." && pwd)"
NAME="agent-production-system-60s"
DEST="$REPO/static/video"

[[ -f "$ROOT/out/$NAME.mp4" ]] || {
  echo "no video at out/$NAME.mp4 — run './build_video.sh all' first" >&2
  exit 1
}

mkdir -p "$DEST"
cp -f "$ROOT/out/$NAME.mp4" "$DEST/"
cp -f "$ROOT/out/$NAME-poster.jpg" "$DEST/"
echo "staged -> $DEST"
ls -lh "$DEST"

[[ "${1:-}" == "--stage" ]] && exit 0

cd "$REPO"
echo
echo "starting hugo server (drafts on) — preview at:"
echo "  http://localhost:1313/posts/agent-production-system-video-preview/"
exec hugo server -D --disableFastRender
