#!/usr/bin/env python3
"""Build data/series/agent-production-system.yaml from post front matter.

Status is NOT stored. The live series table shortcode computes Live vs
Scheduled vs Held at Hugo build time from date + draft, so the daily
Pages rebuild flips a row without a commit.

Usage:
    python3 scripts/sync-series-schedule.py          # write yaml
    python3 scripts/sync-series-schedule.py --check  # exit 1 if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / "content" / "posts"
OUT = ROOT / "data" / "series" / "agent-production-system.yaml"
SERIES = "Agent production system"


def parse_fm(text: str) -> dict[str, str] | None:
    if not text.startswith("+++"):
        return None
    parts = text.split("+++", 2)
    if len(parts) < 3:
        return None
    fm = parts[1]
    fields: dict[str, str] = {}
    for key in ("title", "date", "draft", "series_weight"):
        m = re.search(rf"^{key}\s*=\s*(.+)$", fm, re.M)
        if m:
            fields[key] = m.group(1).strip().strip('"')
    if f'series = ["{SERIES}"]' not in fm and f"series = ['{SERIES}']" not in fm:
        # allow multiline / extra spaces
        if not re.search(
            rf'^series\s*=\s*\[\s*["\']{re.escape(SERIES)}["\']\s*\]',
            fm,
            re.M,
        ):
            return None
    return fields


def collect() -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for path in sorted(POSTS.glob("*.md")):
        fields = parse_fm(path.read_text(encoding="utf-8"))
        if not fields or "series_weight" not in fields or "date" not in fields:
            continue
        title = fields.get("title", path.stem)
        draft = fields.get("draft", "false").lower() == "true"
        rows.append(
            {
                "weight": int(fields["series_weight"]),
                "slug": path.stem,
                "title": title,
                "date": fields["date"],
                "draft": draft,
            }
        )
    rows.sort(key=lambda r: r["weight"])
    return rows


def render_yaml(rows: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/sync-series-schedule.py — do not hand-edit.",
        "# Status is computed at Hugo build time from date + draft.",
        "series: Agent production system",
        "parts:",
    ]
    for r in rows:
        title = str(r["title"]).replace('"', '\\"')
        draft = "true" if r["draft"] else "false"
        lines.append(f"  - weight: {r['weight']}")
        lines.append(f"    slug: {r['slug']}")
        lines.append(f'    title: "{title}"')
        lines.append(f'    date: "{r["date"]}"')
        lines.append(f"    draft: {draft}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rows = collect()
    if not rows:
        print("error: no Agent production system posts found", file=sys.stderr)
        return 1
    body = render_yaml(rows)
    if args.check:
        if not OUT.is_file():
            print(f"error: missing {OUT.relative_to(ROOT)} — run scripts/sync-series-schedule.py", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != body:
            print(
                f"error: {OUT.relative_to(ROOT)} is stale vs content/posts/ — "
                "run python3 scripts/sync-series-schedule.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK:    series schedule data ({len(rows)} parts)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} parts)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
